"""Figure fitting renderer integration (Program D / WP-D05).

End-to-end proof that the D-04 authority is the single decision point on the
existing image path (``CompilerContext.compile`` -> ``WordRenderer.visit_Image``
-> ``WordWriter._add_fitted_picture``):

* small / wide / tall / landscape figures keep their aspect ratio and stay
  inside the effective content box;
* the frozen baseline small-image behaviour is unchanged;
* an explicitly oversized target width is capped by the profile's resolved
  content width (no profile-ID branching anywhere on the path);
* image relationships and the DOCX package stay intact;
* diagram (vector -> raster) output keeps the existing behaviour;
* repeated conversion is deterministic.

The PNG fixtures are generated by a tiny pure-Python PNG writer so the tests
introduce no new third-party dependency.
"""

from __future__ import annotations

import base64
import contextlib
import io
import struct
import zipfile
import zlib
from pathlib import Path
from typing import Any, Dict, List, Tuple

import pytest
from docx import Document

from md_converter.compiler import CompilerContext
from md_converter.renderer.themes.v15_theme import V15Theme

CONTENT_WIDTH_CM = 21.0 - 2.54 - 2.54
CONTENT_HEIGHT_CM = 29.7 - 2.54 - 2.54

BASE_CONFIG: Dict[str, Any] = {
    "word_com": False,
    "enable_cover": False,
    "toc": False,
    "verbose": False,
}


def _png_data_uri(width: int, height: int) -> str:
    """Return a deterministic solid-colour PNG data URI (no dependencies)."""
    scanline = b"\x00" + bytes((0x2F, 0x54, 0x96)) * width
    raw = scanline * height

    def chunk(tag: bytes, payload: bytes) -> bytes:
        body = tag + payload
        return (
            struct.pack(">I", len(payload))
            + body
            + struct.pack(">I", zlib.crc32(body) & 0xFFFFFFFF)
        )

    ihdr = struct.pack(">IIBBBBB", width, height, 8, 2, 0, 0, 0)
    png = (
        b"\x89PNG\r\n\x1a\n"
        + chunk(b"IHDR", ihdr)
        + chunk(b"IDAT", zlib.compress(raw))
        + chunk(b"IEND", b"")
    )
    return "data:image/png;base64," + base64.b64encode(png).decode("ascii")


def _narrow_content_theme() -> V15Theme:
    """A frozen theme variant with 5.0 cm side margins (content width 11.0 cm).

    Used to exercise the resolved-geometry path end to end without any
    profile-ID branching: the only difference is the effective content box.
    """
    return V15Theme.load_default().with_presentation_overrides(
        {"page": {"margins": {"left": "5cm", "right": "5cm"}}}
    )


NARROW_CONTENT_WIDTH_CM = 21.0 - 5.0 - 5.0


def _compile(
    body: str,
    tmp_path: Path,
    name: str,
    *,
    profile_id: str | None = None,
    theme: Any = None,
) -> Tuple[CompilerContext, Path]:
    """Compile ``body`` through the public compiler context."""
    config = dict(BASE_CONFIG)
    if profile_id is not None:
        config["output_profile"] = profile_id
    if theme is not None:
        config["theme"] = theme
    context = CompilerContext.create(config)
    output = tmp_path / f"{name}.docx"
    with contextlib.redirect_stdout(io.StringIO()):
        context.compile(body, {"title": name}, output)
    return context, output


def _shapes(path: Path) -> List[Any]:
    """Return the inline shapes of a rendered artifact."""
    return list(Document(str(path)).inline_shapes)


def _figure_body(width: int, height: int, alt: str = "figure") -> str:
    """Markdown body containing exactly one generated PNG figure."""
    return f"# Figure\n\n![{alt}]({_png_data_uri(width, height)})\n"


def test_baseline_small_image_behaviour_is_unchanged(tmp_path: Path) -> None:
    """82x41 (2:1) figure keeps the accepted target width (min(image_width, width))."""
    _, output = _compile(_figure_body(82, 41), tmp_path, "small")
    shapes = _shapes(output)

    assert len(shapes) == 1
    assert shapes[0].width.cm == pytest.approx(12.7, abs=0.01)
    assert shapes[0].height.cm == pytest.approx(6.35, abs=0.01)
    assert shapes[0].width.cm <= CONTENT_WIDTH_CM


def test_tall_figure_is_scaled_to_the_content_height(tmp_path: Path) -> None:
    """30x70 figure: height bound applies, aspect ratio preserved, no overflow."""
    context, output = _compile(_figure_body(30, 70), tmp_path, "tall")
    shape = _shapes(output)[-1]

    assert shape.height.cm == pytest.approx(CONTENT_HEIGHT_CM, abs=0.05)
    assert shape.width.cm == pytest.approx(CONTENT_HEIGHT_CM * 30 / 70, abs=0.05)
    assert shape.height.cm / shape.width.cm == pytest.approx(70 / 30, rel=0.01)
    assert context.rendered_qa_result is not None
    assert context.rendered_qa_result.metrics["figure_overflow"] == 0


def test_wide_figure_target_is_capped_by_the_content_width(tmp_path: Path) -> None:
    """The frozen 12.7 cm target is capped by a narrower effective content width."""
    _, output = _compile(_figure_body(400, 100), tmp_path, "wide", theme=_narrow_content_theme())
    shape = _shapes(output)[-1]

    assert shape.width.cm == pytest.approx(NARROW_CONTENT_WIDTH_CM, abs=0.02)
    assert shape.height.cm == pytest.approx(NARROW_CONTENT_WIDTH_CM / 4.0, abs=0.02)
    assert shape.width.cm <= NARROW_CONTENT_WIDTH_CM + 0.02


def test_landscape_figure_keeps_its_aspect_ratio(tmp_path: Path) -> None:
    """Landscape figure: aspect ratio preserved end to end (no crop, no stretch)."""
    _, output = _compile(_figure_body(200, 80), tmp_path, "landscape")
    shape = _shapes(output)[-1]

    assert shape.width.cm / shape.height.cm == pytest.approx(2.5, rel=0.01)
    assert shape.height.cm == pytest.approx(12.7 / 2.5, abs=0.02)


@pytest.mark.parametrize(
    ("profile_id", "expected_content_width_cm"),
    [
        ("professional_report", CONTENT_WIDTH_CM),
        ("academic", 21.0 - 3.0 - 3.0),
        ("business_report", 21.0 - 2.0 - 2.0),
    ],
)
def test_profile_geometry_drives_figure_fitting(
    tmp_path: Path, profile_id: str, expected_content_width_cm: float
) -> None:
    """Every profile keeps the frozen target width, which fits every profile box."""
    _, output = _compile(
        _figure_body(400, 100),
        tmp_path,
        profile_id,
        profile_id=profile_id,
    )
    shape = _shapes(output)[-1]

    # Frozen SPEC-FUNC-023 target: min(configured image_width, effective width).
    assert shape.width.cm == pytest.approx(min(12.7, expected_content_width_cm), abs=0.02)
    assert shape.width.cm <= expected_content_width_cm + 0.02


def test_resolved_geometry_variation_changes_the_delivered_figure(tmp_path: Path) -> None:
    """Only the resolved content width differs -> the fitted figure width differs."""
    _, wide_box = _compile(_figure_body(400, 100), tmp_path, "geometry_wide")
    _, narrow_box = _compile(
        _figure_body(400, 100), tmp_path, "geometry_narrow", theme=_narrow_content_theme()
    )

    wide_shape = _shapes(wide_box)[0]
    narrow_shape = _shapes(narrow_box)[0]

    assert wide_shape.width.cm == pytest.approx(12.7, abs=0.02)
    assert narrow_shape.width.cm == pytest.approx(NARROW_CONTENT_WIDTH_CM, abs=0.02)
    assert narrow_shape.width.cm < wide_shape.width.cm
    # Aspect ratio is identical in both boxes: only scale changed.
    assert narrow_shape.width.cm / narrow_shape.height.cm == pytest.approx(4.0, rel=0.01)
    assert wide_shape.width.cm / wide_shape.height.cm == pytest.approx(4.0, rel=0.01)


def test_image_relationship_and_package_integrity(tmp_path: Path) -> None:
    """Fitting must not break the image part, its relationship or the package."""
    _, output = _compile(_figure_body(30, 70), tmp_path, "integrity")

    document = Document(str(output))
    assert len(document.inline_shapes) == 1
    image_parts = [part for part in document.part.package.parts if "image" in part.content_type]
    assert image_parts, "the rendered package must still contain the image part"

    with zipfile.ZipFile(output) as archive:
        media = [name for name in archive.namelist() if name.startswith("word/media/")]
        assert media, "word/media must keep the embedded picture"
        assert archive.testzip() is None


def test_repeated_conversion_is_deterministic(tmp_path: Path) -> None:
    """Same input and config -> identical rendered figure geometry."""
    _, first = _compile(_figure_body(200, 80), tmp_path, "det1")
    _, second = _compile(_figure_body(200, 80), tmp_path, "det2")

    first_shape = _shapes(first)[0]
    second_shape = _shapes(second)[0]
    assert first_shape.width.cm == pytest.approx(second_shape.width.cm)
    assert first_shape.height.cm == pytest.approx(second_shape.height.cm)


def test_generated_diagram_figure_keeps_the_existing_behaviour(tmp_path: Path) -> None:
    """A diagram-derived image still renders inside the content box."""
    body = (
        "# Diagram\n\n"
        "```\n"
        "┌──────────┐\n"
        "│ diagram  │\n"
        "└────┬─────┘\n"
        "     │\n"
        "     ▼\n"
        "┌──────────┐\n"
        "│  end     │\n"
        "└──────────┘\n"
        "```\n"
    )
    context, output = _compile(body, tmp_path, "diagram")
    shapes = _shapes(output)

    assert shapes, "the diagram fallback image must still be rendered"
    for shape in shapes:
        assert shape.width.cm <= CONTENT_WIDTH_CM + 0.05
        assert shape.height.cm <= CONTENT_HEIGHT_CM + 0.05
    assert context.rendered_qa_result is not None
    assert context.rendered_qa_result.metrics["figure_overflow"] == 0


def test_narrow_figure_below_min_width_still_reports_render005(tmp_path: Path) -> None:
    """Readability-floor reporting is unchanged by the D-05 integration."""
    context, output = _compile(_figure_body(10, 100), tmp_path, "narrow")
    shape = _shapes(output)[-1]
    codes = [diagnostic.code for diagnostic in context.diag.diagnostics]

    assert shape.width.cm < 8.0
    assert "RENDER005" in codes
    assert context.rendered_qa_result is not None
    assert context.rendered_qa_result.metrics["figure_below_min_width"] >= 1
